"""
Django settings for portal_cao project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=(oh_r!=o)f0b2zs!mmg!@n^pvu^z1n!zus!3&v_u!m#xj7-ca'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['172.18.66.164','127.0.0.1']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'portal_cao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portal_cao.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

#DATABASES = {
#    'default': {
#        'ENGINE': 'mssql',
#        'NAME': 'RSS2',
#        'USER': 'cao',
#        'PASSWORD': 'P@ssw0rd',
#        'HOST':'172.18.40.172', 
#        'PORT':'1433',
#        'OPTION': {
#            'driver': 'ODBC Driver 17 for SQL Server',
#            }
#    }
#}

#KATANYA VERSION DJANGO GA SUPPORT
#DATABASES = {
#    'default': {
#        'ENGINE': 'sql_server.pyodbc',
#        'NAME': 'RSS2',
#        'HOST': '172.18.40.172',
#        'USER': 'cao',
#        'PASSWORD': 'P@ssw0rd',
#        'PORT': '1433',
#        'OPTIONS': {
#            'driver': 'FreeTDS',
#                   }
#    },
#}

DATABASES = {
    "default": {
        "NAME": "BRIICSS",
        "ENGINE": "django.db.backends.sqlite3",
        "USER": "ANGGITIA",
        "PASSWORD": "",
        "PORT":"1433",
        
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': 'BRIICSS',
    #     'USER': 'LAPTOP-A1BP8DFL/sidiq',
    #     'PASSWORD': '',
    #     'HOST':'localhost',
    #     'PORT':'1433',
    # }
    # "users": {
    #     "NAME": "portal_cao",
    #     "ENGINE": "django.db.backends.mysql",
    #     "USER": "root",
    #     "PASSWORD": "112233",
    # },
    # "BRIVA": {
    #     "NAME": "data_cleansing",
    #     "ENGINE": "django.db.backends.mysql",
    #     "USER": "root",
    #     "PASSWORD": "112233",
    # },
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = '/success/'  # Change this to your desired redirect URL after login
LOGOUT_REDIRECT_URL = '/login/'  # Change this to your desired redirect URL after logout