# Generated by Django 5.0.1 on 2024-02-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='CleansingBank',
            fields=[
                ('NO', models.BigAutoField(default=True)),
                ('TRX_TYPE', models.CharField(max_length=50)),
                ('MNT_STATUS', models.CharField(max_length=50)),
                ('ISPROCESS', models.CharField(max_length=50)),
                ('ISGENERATE', models.CharField(max_length=50)),
                ('ISCHANGE', models.CharField(max_length=255)),
                ('SOR_POTONG', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturBankLain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandi_kliring', models.CharField(max_length=255)),
                ('nama_bank', models.CharField(max_length=255)),
                ('BIC', models.CharField(max_length=255)),
                ('kode_wilayah', models.CharField(max_length=255)),
                ('nama_wilayah', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
