# Generated by Django 5.0.1 on 2024-03-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_checknumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_parent', models.IntegerField(blank=True, null=True)),
                ('name_app', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_app', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
