# Generated by Django 5.0.1 on 2024-03-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_kodebankdummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleansingBank',
            fields=[
                ('NO', models.BigAutoField(default=True)),
                ('TRX_TYPE', models.CharField(max_length=50)),
                ('MNT_STATUS', models.CharField(max_length=50)),
                ('ISPROCESS', models.CharField(max_length=50)),
                ('ISGENERATE', models.CharField(max_length=50)),
                ('ISCHANGE', models.CharField(max_length=255)),
                ('SOR_POTONG', models.BooleanField(default=True)),
            ],
        ),
    ]
